---
# cf. https://gist.github.com/rothgar/8793800
# Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
# Will include all hosts the playbook is run on.
# Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item]['ansible_' + iface].ipv4.address }} {{item}}" state=present
  with_items: groups['all']
  when: (hostvars[item]['ansible_' + iface] is defined) and (ansible_hostname != item) and (ansible_hostname != 'localhost')
  become: yes
