---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  require_ansible_repo: true
  ansible_version: 1.9.1-1.el6
  ansible_verbose: true
  ansible_verbosity: 2
  playbook: kitchen-docker.yml
  hosts: localhost

platforms:
  - name: centos6
    driver_config:
      image: centos:6
      platform: rhel
      run_command: /usr/bin/supervisord -c /var/tmp/docker-supervisord.conf
      use_cache: true
      wait_for_sshd: true
      provision_command:
        # hostkey 作成する
        - service sshd start && service sshd stop
        # initscripts はこのファイルが無いとエラーになる(serviceのテストが失敗する)
        - touch /etc/sysconfig/network
        # easy_install をインストールする
        - yum -y install python-setuptools
        - easy_install supervisor==3.1.3
        # supervisor 用の設定ファイル作成
        - echo '[supervisord]' >> /var/tmp/docker-supervisord.conf
        - echo 'nodaemon=true' >> /var/tmp/docker-supervisord.conf
        - echo '[program:sshd]' >> /var/tmp/docker-supervisord.conf
        - echo 'command=/usr/sbin/sshd -D -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes -o UsePrivilegeSeparation=no -o PidFile=/tmp/sshd.pid' >> /var/tmp/docker-supervisord.conf
        - echo '[include]' >> /var/tmp/docker-supervisord.conf
        # Recursive includes from included files are not supported.
        # cf. http://supervisord.org/configuration.html
        - echo 'files = /etc/supervisord.conf /etc/supervisord.d/*.ini' >> /var/tmp/docker-supervisord.conf
        # # jinja2 が古過ぎて動かないので更新する
        - easy_install pip
        - pip install -U jinja2===2.7.3

suites:
  - name: default
